sudo: required
services:
    - docker

before_install:
    - docker build -t thanapongsj/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true thanapongsj/react-test npm test

after_success:
    - docker build -t thanapongsj/fibo-client ./client
    - docker build -t thanapongsj/fibo-nginx ./nginx
    - docker build -t thanapongsj/fibo-server ./server
    - docker build -t thanapongsj/fibo-worker ./worker
    # Login to the docker CLI
    # Create docker id & docker password in Travis
    - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID"  --password-stdin
    # Take those images and push them to docker hub
    - docker push thanapongsj/fibo-client
    - docker push thanapongsj/fibo-nginx
    - docker push thanapongsj/fibo-server
    - docker push thanapongsj/fibo-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: fibo-react-docker
    env:  FiboReactDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-1-811572040291
    bucket_path: fibo-react-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
